server:
  port: ${PORT:8080}        # Railway injects PORT; 8080 locally

spring:
  application:
    name: todo_cloud
  data:
    mongodb:
      uri: ${MONGODB_CONNECTION_STRING}
      auto-index-creation: true

jwt:
  secret: ${JWT_SECRET_BASE64}
